import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const output = 'tool-results/admin-qa'; await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true });
const errors = [];
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const page = await context.newPage();
  page.setDefaultNavigationTimeout(120000);
  page.setDefaultTimeout(60000);
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  await page.goto('http://localhost:8091/login');
  await page.getByLabel('Email').fill('super@admin-test.invalid');
  await page.getByLabel('Password', { exact: true }).fill('Local-QA-only-428!');
  await page.getByRole('button', { name: /sign in/i }).click();
  await page.waitForURL('**/admin', { timeout: 60000 });
  await page.getByText('Your application, growing', { exact: true }).waitFor();
  await page.waitForTimeout(1200);
  await page.screenshot({ path: `${output}/overview-desktop.png`, fullPage: true });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.getByRole('button', { name: 'Collapse sidebar', exact: true }).click();
  await page.waitForTimeout(300);
  await page.reload();
  await page.getByRole('button', { name: 'Expand sidebar', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Expand sidebar', exact: true }).click();
  await page.keyboard.press('Control+k');
  await page.getByLabel('Global admin search').fill('Alex');
  await page.getByRole('dialog').getByRole('link', { name: /Alex Chen/ }).waitFor();
  await page.keyboard.press('Enter');
  await page.waitForURL('**/admin/users/qa-member');
  await page.getByRole('heading', { name: 'Alex Chen', exact: true }).waitFor();
  console.log('PASS login, sidebar persistence, keyboard search, user profile.');
  const routes = ['users', 'activity', 'analytics', 'productivity', 'learning', 'reports', 'plans', 'subscriptions', 'payments', 'content', 'feedback', 'support', 'notifications', 'audit', 'settings', 'account', 'schedules'];
  for (const route of routes) {
    await page.goto(`http://localhost:8091/admin/${route}`);
    await page.locator('.ad-page-heading h1').waitFor({ timeout: 60000 });
    await page.waitForFunction(() => !document.querySelector('[aria-label="Loading records"]'), { timeout: 30000 });
    assert.equal(await page.locator('.ad-error').count(), 0, `${route} has no API error`);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `${route} page overflow`);
    console.log(`PASS /admin/${route}`);
  }
  await page.goto('http://localhost:8091/admin/users');
  await page.getByRole('button', { name: 'Add user', exact: true }).click();
  await page.getByLabel('Full name').fill('UI created member');
  await page.getByLabel('Email', { exact: true }).fill(`browser-${Date.now()}@admin-test.invalid`);
  await page.getByLabel('Initial password').fill('Local-UI-test-819!');
  await page.getByRole('button', { name: 'Save changes' }).click();
  await page.getByText('User account saved.', { exact: true }).waitFor();
  await page.getByRole('textbox', { name: 'Search name or email…' }).fill('UI created');
  await page.getByRole('link', { name: /UI created member/ }).first().waitFor();
  await page.screenshot({ path: `${output}/users-desktop.png`, fullPage: true });
  await page.goto('http://localhost:8091/admin/reports');
  await page.getByRole('button', { name: 'Generate report', exact: true }).click();
  await page.getByLabel('Report name').fill('Browser-generated report');
  await page.getByLabel('Report type').selectOption('usage');
  await page.getByRole('button', { name: 'Save changes' }).click();
  await page.getByText('Your report is ready to preview and download.').waitFor();
  console.log('PASS user creation, user search, and report generation through UI.');
  await page.goto('http://localhost:8091/admin');
  await page.getByText('Your application, growing', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Change theme' }).click();
  await page.getByRole('menuitem', { name: /^Dark/ }).click();
  await page.waitForFunction(() => document.querySelector('.admin-root')?.getAttribute('data-theme') === 'dark');
  await page.waitForTimeout(1000);
  await page.screenshot({ path: `${output}/overview-dark.png`, fullPage: true });
  await page.reload();
  await page.waitForFunction(() => document.querySelector('.admin-root')?.getAttribute('data-theme') === 'dark');
  await page.getByRole('button', { name: 'Change theme' }).click();
  await page.getByRole('menuitem', { name: /^Light/ }).click();
  for (const width of [768, 390, 320]) {
    await page.setViewportSize({ width, height: width === 768 ? 1024 : 844 });
    await page.goto('http://localhost:8091/admin');
    await page.getByText('Your application, growing', { exact: true }).waitFor();
    await page.waitForTimeout(1000);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `overflow ${width}px`);
    await page.screenshot({ path: `${output}/overview-${width}.png`, fullPage: true });
    await page.getByRole('button', { name: 'Open admin menu' }).click();
    await page.getByRole('dialog').getByRole('navigation').waitFor();
    await page.waitForTimeout(300);
    const drawerBounds = await page.getByRole('dialog').boundingBox();
    assert.equal(drawerBounds.x, 0);
    assert.equal(drawerBounds.y, 0);
    await page.screenshot({ path: `${output}/menu-${width}.png` });
    await page.keyboard.press('Escape');
    await page.getByRole('dialog').waitFor({ state: 'detached' });
    assert.equal(await page.getByRole('dialog').count(), 0);
  }
  await page.emulateMedia({ reducedMotion: 'reduce' });
  assert.equal(await page.locator('.ad-main').evaluate(el => getComputedStyle(el).animationName), 'none');
  console.log('PASS dark mode persistence, tablet/mobile layouts, accessible drawer, reduced motion.');
  await page.goto('http://localhost:8091/');
  await page.getByRole('region', { name: 'Small steps. A life in bloom.' }).waitFor();
  assert.equal(await page.getByRole('navigation', { name: 'Main navigation' }).getByRole('link', { name: 'Admin Console' }).count(), 1);
  await page.goto('http://localhost:8091/community');
  await page.getByRole('button', { name: 'resources', exact: true }).click();
  await page.getByRole('heading', { name: 'Welcome to the community' }).first().waitFor();
  await page.goto('http://localhost:8091/admin');
  await page.getByRole('button', { name: 'Admin profile menu' }).click();
  await page.getByRole('menuitem', { name: 'Sign out' }).click();
  await page.waitForURL('**/login');
  console.log('PASS personal dashboard, community resources, and logout regression.');
  assert.deepEqual(errors, []);
  console.log('PASS no browser console errors.');
} finally { await browser.close(); }
