'use client';
import { useEffect, useState } from 'react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis, Legend, Brush } from 'recharts';

export default function GrowthChart({ data, metric = 'activities', zoom = false }: { data: any[]; metric?: string; zoom?: boolean }) {
  const [animate, setAnimate] = useState(() => typeof window !== 'undefined' && !matchMedia('(prefers-reduced-motion: reduce)').matches);
  useEffect(() => { const media = matchMedia('(prefers-reduced-motion: reduce)'); const sync = () => setAnimate(!media.matches); sync(); media.addEventListener('change', sync); return () => media.removeEventListener('change', sync); }, []);
  return <div className="ad-chart" role="img" aria-label="Application growth chart. The accessible data table below contains all values."><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{ top: 15, right: 18, left: -18, bottom: 0 }}><defs><linearGradient id="admin-growth-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#20aa83" stopOpacity={0.24} /><stop offset="95%" stopColor="#20aa83" stopOpacity={0.01} /></linearGradient></defs><CartesianGrid stroke="var(--ad-line)" vertical={false} strokeDasharray="3 5" /><XAxis dataKey="date" tickFormatter={value => new Date(value).toLocaleDateString('en', { day: 'numeric', month: 'short', timeZone: 'UTC' })} tick={{ fill: 'var(--ad-muted)', fontSize: 11 }} tickLine={false} axisLine={false} minTickGap={30} /><YAxis allowDecimals={false} tick={{ fill: 'var(--ad-muted)', fontSize: 11 }} tickLine={false} axisLine={false} /><Tooltip contentStyle={{ background: 'var(--ad-surface)', border: '1px solid var(--ad-line)', borderRadius: 12, color: 'var(--ad-text)' }} /><Legend formatter={(value) => <span style={{ color: 'var(--ad-muted)' }}>{value}</span>} iconType="circle" iconSize={7} wrapperStyle={{ fontSize: 12, paddingTop: 15 }} /><Area type="monotone" dataKey={metric} name={metric === 'active' ? 'Active contributors' : 'Tracker records'} stroke="#149d79" strokeWidth={2.5} fill="url(#admin-growth-fill)" isAnimationActive={animate} animationDuration={900} /><Area type="monotone" dataKey="registrations" name="New users" stroke="#8a95b9" strokeWidth={1.8} strokeDasharray="5 5" fill="transparent" isAnimationActive={animate} animationDuration={900} />{zoom && <Brush dataKey="date" height={20} stroke="#8a95b9" />}</AreaChart></ResponsiveContainer></div>;
}

