'use client';
import { useState } from 'react';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import { Users, Activity, CheckCheck, ArrowUpRight, TrendingUp, BookOpen, Sparkles, ArrowRight } from 'lucide-react';
import { useAdmin } from './admin-shell';
import { can } from '@/lib/admin/permissions';
import { DateFilter, ErrorNotice, Loading, PageHeading, Panel, Stat, useAdminData, money } from './admin-ui';
const Chart = dynamic(() => import('./admin-charts'), { ssr: false, loading: () => <div className="ad-chart ad-chart-skeleton" /> });

export function Dashboard({ analytics = false }: { analytics?: boolean }) {
  const actor = useAdmin(); const [period, setPeriod] = useState('30'), [metric, setMetric] = useState('activities');
  const [start, setStart] = useState(new Date(Date.now() - 29 * 86400000).toISOString().slice(0, 10)), [end, setEnd] = useState(new Date().toISOString().slice(0, 10));
  const query = period === 'custom' ? `start=${start}&end=${end}` : `days=${period}`;
  const { data, loading, error, refresh } = useAdminData(`${analytics ? 'analytics' : 'dashboard'}?${query}`);
  return <>
    <PageHeading eyebrow={analytics ? 'MEASURE WHAT MATTERS' : 'YOUR COMMUNITY, IN FOCUS'} title={analytics ? 'Application analytics' : `Welcome back, ${actor.name?.split(' ')[0] || 'Admin'}.`} description={analytics ? 'Understand the patterns behind everyday progress.' : 'A clearer view of your community and the progress you’re making together.'}><button className="ad-button" onClick={refresh}>Refresh</button><DateFilter value={period} onChange={setPeriod} /></PageHeading>
    {period === 'custom' && <div className="ad-toolbar"><label>From <input className="ad-input" type="date" value={start} onChange={e => setStart(e.target.value)} /></label><label>To <input className="ad-input" type="date" value={end} onChange={e => setEnd(e.target.value)} /></label></div>}
    {error ? <ErrorNotice message={error} retry={refresh} /> : loading || !data ? <Loading /> : <>
      <div className="ad-stats-grid"><Stat label="Total users" value={data.totalUsers} description={<><span className="ad-trend"><TrendingUp size={13} />{data.growth === null ? `${data.newUsers} new` : `${data.growth > 0 ? '+' : ''}${data.growth}%`}</span> {data.growth === null ? 'in this period' : 'registrations vs previous period'}</>} icon={<Users size={18} />} /><Stat label="Daily active users" value={data.active.daily} description={`${data.active.weekly} weekly · ${data.active.monthly} monthly`} icon={<Activity size={18} />} /><Stat label="Tracked activities" value={data.activityCount} description="Saved records in the selected period" icon={<Sparkles size={18} />} /><Stat label="Goals & actions completed" value={data.productivity.completed} description={`${data.productivity.completion}% completion · all time`} icon={<CheckCheck size={18} />} accent="ad-stat-featured" /></div>
      <div className="ad-dashboard-grid"><Panel title="Your application, growing" subtitle="Small actions. Meaningful momentum." className="ad-growth-panel" actions={<span className="ad-live"><i />Live database</span>}><div className="ad-chart-summary"><strong>{data.activityCount.toLocaleString()}<span>tracked activities</span></strong><div className="ad-segmented"><button className={metric === 'activities' ? 'active' : ''} onClick={() => setMetric('activities')}>Activity</button><button className={metric === 'active' ? 'active' : ''} onClick={() => setMetric('active')}>Contributors</button></div></div><Chart data={data.graph} metric={metric} zoom={analytics && data.graph.length > 30} /><details className="ad-chart-data"><summary>View chart data</summary><div className="ad-table-scroll"><table><caption className="sr-only">Daily activity and user growth</caption><thead><tr><th>Date (UTC)</th><th>Records</th><th>Contributors</th><th>New users</th></tr></thead><tbody>{data.graph.map((r: any) => <tr key={r.date}><td>{r.date}</td><td>{r.activities}</td><td>{r.active}</td><td>{r.registrations}</td></tr>)}</tbody></table></div></details></Panel>
      <Panel title="Where growth happens" subtitle="Feature usage in this period" className="ad-feature-panel"><div className="ad-feature-list">{data.features.length ? data.features.slice(0, 7).map((feature: any, index: number) => <div className="ad-feature" key={feature.name}><div><span><i style={{ background: ['#20a481', '#7c8cbe', '#d7a04c', '#59a4b0'][index % 4] }} />{feature.name}</span><strong>{feature.count.toLocaleString()}</strong></div><div className="ad-meter"><span style={{ width: `${Math.max(2, feature.count / Math.max(data.activityCount, 1) * 100)}%`, background: ['#20a481', '#7c8cbe', '#d7a04c', '#59a4b0'][index % 4] }} /></div></div>) : <p className="ad-muted">Feature usage appears when members save their first activity.</p>}</div><div className="ad-feature-footer"><span>Tracked across LIFEOS</span><ArrowUpRight size={18} /></div></Panel></div>
      <div className="ad-bottom-grid"><Panel title="Everyday progress" subtitle="Consistency is built one action at a time."><div className="ad-progress-summary"><div className="ad-donut" style={{ '--progress': `${data.productivity.completion}%` } as React.CSSProperties}><span><strong>{data.productivity.completion}%</strong><small>completed</small></span></div><div className="ad-progress-numbers"><p><i />{data.productivity.completed} <span>completed goals & actions</span></p><p><i />{data.productivity.pending} <span>still in progress</span></p>{can(actor.permissions, 'productivity.read') && <Link href="/admin/productivity">Explore productivity <ArrowRight size={15} /></Link>}</div></div></Panel><Panel title="Learning is a daily practice" subtitle="Recorded learning, during this period."><div className="ad-learning-highlight"><span><BookOpen size={25} /></span><div><strong>{Math.round(data.productivity.learningMinutes / 60 * 10) / 10}<small>hours learned</small></strong><p>{data.productivity.learningSessions} sessions · {data.productivity.habits} habit completions</p></div></div>{can(actor.permissions, 'productivity.read') && <Link className="ad-text-link" href="/admin/learning">View learning progress <ArrowUpRight size={16} /></Link>}</Panel></div>
      {analytics && <><div className="ad-stats-grid"><Stat label="Recorded logins" value={data.logins} description="History starts with this admin upgrade" icon={<Activity size={18} />} /><Stat label="Average saved daily score" value={data.dailyScore === null ? '—' : Math.round(data.dailyScore)} description={`${data.scoredDays} saved daily scores in this period`} icon={<TrendingUp size={18} />} /><Stat label="New registrations" value={data.newUsers} description={`${data.previousUsers} in the previous equivalent period`} icon={<Users size={18} />} /><Stat label="Session duration" value="Not tracked" description="No page-duration telemetry is installed" icon={<Activity size={18} />} /></div><Panel title="Billing overview" subtitle="Manual ledger records, grouped by currency. No payment provider is connected.">{data.revenue.length ? <div className="ad-inline-metrics">{data.revenue.map((r: any) => <div key={r.currency + r.status}><small>{r.currency} · {r.status}</small><strong>{money(r.cents, r.currency)}</strong><span>{r.count} records</span></div>)}</div> : <p className="ad-panel-note">No billing figures available for your role or this period.</p>}</Panel><p className="ad-note">Retention cohorts, conversion funnels, payment-provider events, and session duration are not currently collected. They are not inferred from tracker records.</p></>}
      <p className="ad-note">{data.definitions}</p>
    </>}
  </>;
}
