'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Plus, Pencil, Trash2, ArrowUpRight, Users, Activity, ShieldCheck, Columns3 } from 'lucide-react';
import { can } from '@/lib/admin/permissions';
import { adminFetch, useAdmin } from './admin-shell';
import { Badge, Confirm, Empty, ErrorNotice, Loading, PageHeading, Pager, Panel, SearchInput, Stat, dateText, money, useAdminData, useDebounce } from './admin-ui';
import { RecordEditor } from './admin-records';

export function UsersPage() {
  const actor = useAdmin(); const writable = can(actor.permissions, 'users.write'), deletable = can(actor.permissions, 'users.delete');
  const [q, setQ] = useState(''), [status, setStatus] = useState(''), [role, setRole] = useState(''), [page, setPage] = useState(1), [sort, setSort] = useState('createdAt'), [direction, setDirection] = useState('desc');
  const query = useDebounce(q); const { data, loading, error, refresh } = useAdminData(`users?q=${encodeURIComponent(query)}&status=${status}&role=${role}&page=${page}&sort=${sort}&direction=${direction}`);
  const { data: roles } = useAdminData<any[]>('roles');
  const [selected, setSelected] = useState<string[]>([]), [editing, setEditing] = useState<any>(undefined), [confirm, setConfirm] = useState<any>(null), [notice, setNotice] = useState('');
  const [columns, setColumns] = useState(['role', 'status', 'subscription', 'lastActiveAt', 'createdAt', 'activity']);
  useEffect(() => { setSelected([]); }, [page, query, status, role]);
  const sortBy = (field: string) => { setSort(field); setDirection(sort === field && direction === 'asc' ? 'desc' : 'asc'); setPage(1); };
  return <><PageHeading eyebrow="PEOPLE FIRST" title="Your community" description="Know your members. Support their next step.">{writable && <button className="ad-button primary" onClick={() => setEditing(null)}><Plus size={17} />Add user</button>}<a className="ad-button" href={`/api/admin/users/export?q=${encodeURIComponent(query)}&status=${status}&role=${role}&sort=${sort}&direction=${direction}`}>Export CSV</a></PageHeading>{notice && <p role="status" className="ad-success">{notice}</p>}<Panel><div className="ad-toolbar"><SearchInput value={q} onChange={v => { setQ(v); setPage(1); }} placeholder="Search name or email…" /><select className="ad-select" aria-label="Filter user status" value={status} onChange={e => { setStatus(e.target.value); setPage(1); }}><option value="">All current users</option>{['active', 'suspended', 'deleted'].map(s => <option key={s}>{s}</option>)}</select><select className="ad-select" aria-label="Filter user role" value={role} onChange={e => { setRole(e.target.value); setPage(1); }}><option value="">All roles</option><option value="member">Member</option>{roles?.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select><details className="ad-columns"><summary className="ad-button"><Columns3 size={16} />Columns</summary><div>{['role', 'status', 'subscription', 'lastActiveAt', 'createdAt', 'activity'].map(field => <label key={field}><input type="checkbox" checked={columns.includes(field)} onChange={e => setColumns(e.target.checked ? [...columns, field] : columns.filter(c => c !== field))} />{field.replace('At', '')}</label>)}</div></details></div>
    {selected.length > 0 && <div className="ad-bulk"><strong>{selected.length} selected</strong>{writable && <><button className="ad-button" onClick={() => setConfirm({ ids: selected, status: 'active' })}>Activate</button><button className="ad-button" onClick={() => setConfirm({ ids: selected, status: 'suspended' })}>Suspend</button></>}{deletable && <button className="ad-button danger" onClick={() => setConfirm({ ids: selected, status: 'deleted' })}>Delete accounts</button>}</div>}
    {error ? <ErrorNotice message={error} retry={refresh} /> : loading ? <Loading /> : !data?.items.length ? <Empty title="No users found" description="Try another name, email, or filter." /> : <div className="ad-table-scroll"><table><caption className="sr-only">LIFEOS user management</caption><thead><tr>{(writable || deletable) && <th><input type="checkbox" aria-label="Select all users on this page" checked={data.items.length > 0 && data.items.every((u: any) => selected.includes(u.id))} onChange={e => setSelected(e.target.checked ? data.items.map((u: any) => u.id) : [])} /></th>}<th><button onClick={() => sortBy('name')}>User {sort === 'name' ? direction === 'asc' ? '↑' : '↓' : '↕'}</button></th>{columns.includes('role') && <th>Role</th>}{columns.includes('status') && <th>Status</th>}{columns.includes('subscription') && <th>Plan</th>}{columns.includes('lastActiveAt') && <th><button onClick={() => sortBy('lastActiveAt')}>Last active ↕</button></th>}{columns.includes('createdAt') && <th><button onClick={() => sortBy('createdAt')}>Joined ↕</button></th>}{columns.includes('activity') && <th>Activity</th>}<th>Actions</th></tr></thead><tbody>{data.items.map((user: any) => <tr key={user.id}>{(writable || deletable) && <td><input type="checkbox" aria-label={`Select ${user.email}`} checked={selected.includes(user.id)} onChange={e => setSelected(e.target.checked ? [...selected, user.id] : selected.filter(id => id !== user.id))} /></td>}<td><Link className="ad-user-cell" href={`/admin/users/${user.id}`}><span className="ad-avatar">{(user.name || user.email).charAt(0).toUpperCase()}</span><span><strong>{user.name || 'Member'}</strong><small>{user.email}</small></span></Link></td>{columns.includes('role') && <td><span className="ad-role">{user.role?.name || 'Member'}</span></td>}{columns.includes('status') && <td><Badge value={user.status} /></td>}{columns.includes('subscription') && <td>{user.subscriptions[0]?.plan.name || 'No plan'}</td>}{columns.includes('lastActiveAt') && <td>{dateText(user.lastActiveAt)}</td>}{columns.includes('createdAt') && <td>{dateText(user.createdAt)}</td>}{columns.includes('activity') && <td><strong>{user._count.goals + user._count.improvements + user._count.learningSessions}</strong><small className="ad-cell-subtext">goals, notes, sessions</small></td>}<td><div className="ad-row-actions"><Link href={`/admin/users/${user.id}`} className="ad-icon-button" aria-label={`View ${user.email}`}><ArrowUpRight size={17} /></Link>{writable && <button className="ad-icon-button" onClick={() => setEditing(user)} aria-label={`Edit ${user.email}`}><Pencil size={15} /></button>}{deletable && <button className="ad-icon-button danger-text" onClick={() => setConfirm({ ids: [user.id], status: 'deleted' })} aria-label={`Delete ${user.email}`}><Trash2 size={15} /></button>}</div></td></tr>)}</tbody></table></div>}{data && <Pager page={page} total={data.total} onChange={setPage} />}</Panel>
    {editing !== undefined && <RecordEditor title={editing ? 'Edit member' : 'Add a member'} fields={[{ key: 'name', label: 'Full name' }, { key: 'email', label: 'Email', type: 'email' }, ...(!editing ? [{ key: 'password', label: 'Initial password', type: 'password', help: 'At least 8 characters; application password policy also applies. Share it securely outside this console.' }] : []), { key: 'status', label: 'Account status', options: ['active', 'suspended', ...(deletable ? ['deleted'] : [])] }, ...(actor.roleId === 'super-admin' ? [{ key: 'roleId', label: 'Role', options: ['', ...(roles?.map(r => r.id) || [])], help: 'Blank means Member. Only Super Admin can change roles.' }] : [])]} record={editing} close={() => setEditing(undefined)} save={async payload => { await adminFetch(`users${editing ? '/' + editing.id : ''}`, { method: editing ? 'PATCH' : 'POST', body: JSON.stringify({ ...payload, roleId: actor.roleId === 'super-admin' ? payload.roleId || null : editing?.roleId || null }) }); setNotice('User account saved.'); refresh(); }} />}
    {confirm && <Confirm open title={`${confirm.status === 'deleted' ? 'Delete' : confirm.status === 'suspended' ? 'Suspend' : 'Activate'} ${confirm.ids.length} account(s)?`} description={confirm.status === 'deleted' ? 'Sign-in access and sessions will be removed. Historical tracker records are retained; an administrator can restore the account.' : confirm.status === 'suspended' ? 'These users will be signed out and unable to sign in until activated.' : 'These accounts will be allowed to sign in again.'} danger={confirm.status !== 'active'} close={() => setConfirm(null)} action={async () => { await adminFetch('users/bulk', { method: 'POST', body: JSON.stringify(confirm) }); setSelected([]); setNotice('Account status updated.'); refresh(); }} />}
  </>;
}

export function UserDetail({ id }: { id: string }) {
  const actor = useAdmin(); const { data, loading, error, refresh } = useAdminData(`users/${id}`);
  if (error) return <ErrorNotice message={error} retry={refresh} />;
  if (loading || !data) return <Loading />;
  const { user } = data;
  return <><PageHeading eyebrow="MEMBER PROFILE" title={user.name || 'LIFEOS member'} description={user.email}><Link className="ad-button" href="/admin/users">← All users</Link><Badge value={user.status} /></PageHeading><div className="ad-stats-grid"><Stat label="Role" value={user.role?.name || 'Member'} description={`Joined ${dateText(user.createdAt)}`} icon={<ShieldCheck size={18} />} /><Stat label="Last active" value={dateText(user.lastActiveAt)} description={user.timezone} icon={<Activity size={18} />} /><Stat label="Learning sessions" value={user._count.learningSessions} description="Recorded across all time" icon={<Users size={18} />} /><Stat label="Habit completions recorded" value={user._count.habitCompletions} description="All stored completion records" icon={<Activity size={18} />} /></div>
    <div className="ad-bottom-grid">{can(actor.permissions, 'activity.read') && <Panel title="Account timeline" subtitle="Login history is recorded from the admin upgrade onward.">{data.events.length ? <div className="ad-timeline">{data.events.map((event: any) => <div key={event.id}><i /><div><strong>{event.action}</strong><p>{event.feature} · {new Date(event.createdAt).toLocaleString()}</p></div></div>)}</div> : <Empty title="No account events recorded" />}</Panel>}{can(actor.permissions, 'productivity.read') && <Panel title="Goals & improvement actions" subtitle="Recent records. Personal journal and reflection bodies are not included."><div className="ad-simple-list">{[...data.goals, ...data.improvements].map((r: any) => <div key={r.id}><span>{r.title}</span><Badge value={r.isCompleted || r.completed ? 'completed' : 'pending'} /></div>)}{!data.goals.length && !data.improvements.length && <Empty title="No goals or actions yet" />}</div></Panel>}</div>
    {can(actor.permissions, 'billing.read') && <div className="ad-bottom-grid"><Panel title="Subscriptions"><div className="ad-simple-list">{data.subscriptions.map((s: any) => <div key={s.id}><span>{s.plan.name}<small>{dateText(s.endAt)}</small></span><Badge value={s.status} /></div>)}{!data.subscriptions.length && <Empty title="No subscriptions recorded" />}</div></Panel><Panel title="Payment history"><div className="ad-simple-list">{data.payments.map((p: any) => <div key={p.id}><span>{money(p.amountCents, p.currency)}<small>{p.reference}</small></span><Badge value={p.status} /></div>)}{!data.payments.length && <Empty title="No payments recorded" />}</div></Panel></div>}
    {(can(actor.permissions, 'feedback.read') || can(actor.permissions, 'support.read')) && <Panel title="Feedback & support"><div className="ad-simple-list">{[...data.feedback, ...data.support].map((r: any) => <div key={r.id}><span>{r.title}</span><Badge value={r.status} /></div>)}{!data.feedback.length && !data.support.length && <Empty title="No cases recorded" />}</div></Panel>}
  </>;
}
