'use client';
import { useEffect, useState } from 'react';
import { Bell, BookOpen, MessageSquare, LifeBuoy } from 'lucide-react';

export default function CommunityPage() {
  const [data, setData] = useState<any>(null), [error, setError] = useState(''), [tab, setTab] = useState('inbox'), [busy, setBusy] = useState(false), [notice, setNotice] = useState('');
  const load = async () => { setError(''); try { const response = await fetch('/api/community'); const result = await response.json(); if (!response.ok) throw new Error(result.error); setData(result.data); } catch (e) { setError((e as Error).message); } };
  useEffect(() => { load(); }, []);
  return <div className="max-w-4xl mx-auto space-y-6"><div><h1 className="text-2xl font-semibold">Your LIFEOS community</h1><p className="text-sm text-gray-500 mt-2">Updates, useful resources, and a little help when you need it.</p></div><div className="flex flex-wrap gap-2">{[['inbox', Bell], ['resources', BookOpen], ['feedback', MessageSquare], ['support', LifeBuoy]].map(([key, Icon]: any) => <button key={key} className={`flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm capitalize ${tab === key ? 'bg-emerald-700 text-white' : 'bg-white border border-gray-200'}`} onClick={() => setTab(key)}><Icon size={17} />{key}</button>)}</div>{error && <div role="alert" className="p-4 bg-red-50 text-red-700 rounded-xl">{error} <button onClick={load}>Try again</button></div>}{notice && <p role="status" className="text-emerald-700">{notice}</p>}{!data && !error && <p role="status">Loading your community…</p>}
    {data && (tab === 'inbox' || tab === 'resources') && <div className="space-y-3">{(tab === 'inbox' ? data.notifications : data.content).map((item: any) => <article key={item.id} className="bg-white border border-gray-200 rounded-2xl p-5"><div className="flex justify-between gap-3"><h2 className="font-semibold">{item.notification?.title || item.title}</h2>{tab === 'inbox' && !item.readAt && <button className="text-xs text-emerald-700" onClick={async () => { try { const response = await fetch('/api/community', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id: item.id }) }); if (!response.ok) throw new Error('Could not mark this message read.'); await load(); } catch (e) { setError((e as Error).message); } }}>Mark read</button>}</div><p className="mt-3 text-sm text-gray-600 whitespace-pre-wrap break-words leading-7">{item.notification?.message || item.body}</p><p className="mt-4 text-xs text-gray-400">{new Date(item.createdAt).toLocaleDateString()}</p></article>)}{!(tab === 'inbox' ? data.notifications : data.content).length && <div className="bg-white rounded-2xl border p-10 text-center"><h2 className="font-medium">{tab === 'inbox' ? 'You’re all caught up' : 'Resources are on their way'}</h2><p className="text-gray-500 text-sm mt-2">New community updates will appear here.</p></div>}</div>}
    {(tab === 'feedback' || tab === 'support') && <><form className="p-5 rounded-2xl bg-white border space-y-4" onSubmit={async e => { e.preventDefault(); const form = e.currentTarget; const fields = new FormData(form); setBusy(true); setError(''); try { const response = await fetch('/api/community', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ type: tab, title: fields.get('title'), message: fields.get('message'), ...(tab === 'feedback' ? { kind: fields.get('kind') } : {}) }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); form.reset(); setNotice('Your message has been saved for the team.'); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }}><h2 className="font-semibold">{tab === 'feedback' ? 'Share an idea or report an issue' : 'How can we help?'}</h2><label className="block text-sm">Subject<input name="title" required maxLength={160} className="block w-full border rounded-lg mt-1 p-2" /></label>{tab === 'feedback' && <label className="block text-sm">Type<select name="kind" className="block w-full border rounded-lg mt-1 p-2">{['suggestion', 'bug', 'complaint', 'feature-request'].map(value => <option key={value}>{value}</option>)}</select></label>}<label className="block text-sm">Message<textarea name="message" required maxLength={10000} rows={5} className="block w-full border rounded-lg mt-1 p-2" /></label><button disabled={busy} className="px-4 py-2 rounded-lg bg-emerald-700 text-white disabled:opacity-50">{busy ? 'Submitting…' : 'Submit message'}</button></form><div className="space-y-3">{data?.[tab].map((item: any) => <article key={item.id} className="bg-white border rounded-xl p-4 flex justify-between gap-4"><strong className="text-sm">{item.title}</strong><span className="text-xs text-gray-500 capitalize">{item.status}</span></article>)}</div></>}
  </div>;
}
